### ISSUE TITLE
lldb is missing

### ISSUE THREAD

**Issue by nblog** [xiofee/llvm-build#1]
Suggest adding [`lldb`](https://lldb.llvm.org/)

**Comment by xiofee** [comment]
GitHub Actions limits the execution time of each task to 5 hours, and adding lldb can result in the compilation taking too long and being cancelled.

The following task added lldb, with the compilation option `LLVM_ENABLE_PROJECTS="clang;lld;lldb;clang-tools-extra"`, but it was cancelled due to exceeding the execution time:
[https://github.com/xiofee/llvm-build/actions/runs/4627607974](https://github.com/xiofee/llvm-build/actions/runs/4627607974)

Therefore, I set the compilation option to `LLVM_ENABLE_PROJECTS="clang;lld;clang-tools-extra"`. Although sometimes the task may still be cancelled due to slow speed, but most of the time it can be compiled successfully within the time limit.

If you have a better solution, feel free to submit a pull request or let me know.

**Comment by nblog** [comment]
I'm very sorry, I don't know GitHub Actions, I have a simple idea, is it possible to split the components into multiple projects for compilation (e.g. llvm-lldb, llvm-opt, etc.), and then one repository for integration (llvm-build), to avoid the 5 hour limit.
